development:
  adapter: postgresql
  encoding: unicode
  database: learning-rails-exercism
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: learning-rails-exercism
  pool: 5
  username:
  password:
